.....................'..,clc'.''.
......................,lxolxx:.'
.....................,xk;cl;xk,.
...............''.'.,xk;:00;lO;
...............'''''dO;:OK0;lO;
...............''..c0c;x0K0;lO;.
................'.'xk,lO0XO;oO;.
................'.;0o,xO0Xk,dO,.'
................'.c0:;kO0Xx,xx'.'
................'.oO;:OOKXo;Od....
................'..dO;cO0KKc:0l.
...........'..''..dO,lOOKK::0l.''.....
...........''.....dk;lO0KK:c0c..''......
.....''...........dO;lOOK0;l0:.....'
...........',:llooOO;lOOKK:cKo'......
...'..',cddooolodool':k0KKl'lodd:''.
...'.,lxollolc;;oOOxdc:dKKx;co:ckd,
....,xk:ckKKKX0xllkKKKOk0KKO0K0:;Od
.'..c0c:KOod0KKKK00KKKKKKKKKKKXx,dk
....dO;o0x;'lkKKKKKKKKKKKKKKKKXx,d
.'..xk;oxl;.;k0KKKKKKKKKKKKKKKKc;0d
.'.'d0:;xx::xO0KKKKKKKKKKKKKKKd,xk,
....,okd:':xO0KKKKKKKKKKKKKKKo;dO:.
..''.'x0cckO0KKKKKKKKKKKKKXk::xx;.
.....:Oo;xO0KKKKKKKKKKKKKOl;okl'..
'....;Oo;xO0KKKKKKKKKKKOl:lxo,.''.'...
...'.'oOc:kKKKKKKKKKKOl:oxo,.
......'oO:c0KKKKKKK0o:oxo,
......'oO;'dO0KK0K0c:Od,.'
.''..,dOccoccccccl:.oO;.'.''.'.
'..,lxd;ckO0Okxdoo,.l0d,''..